general:
	go build main.go helper.go setup.go stats.go
	./main general
	rm main

artistUnique:
	go build main.go helper.go setup.go stats.go
	./main artist unique
	rm main

artistTime:
	go build main.go helper.go setup.go stats.go
	./main artist time
	rm main

trackUnique:
	go build main.go helper.go setup.go stats.go
	./main track unique
	rm main

trackTime:
	go build main.go helper.go setup.go stats.go
	./main track time
	rm main

all:
	go build main.go helper.go setup.go stats.go
	./main all
	rm main

http:
	go build main.go backend.go helper.go setup.go stats.go
	./main
	rm main